IMAGE_SIZE = 28
INPUT_LAYER_SIZE = IMAGE_SIZE * IMAGE_SIZE
OUTPUT_LAYER_SIZE = 10

hidden_layer_size = 800
hidden_layer_number = 6
MODEL_FOLDER_NAME = './models/pa1-{}'.format(hidden_layer_number + 1)
DROPOUT_RATE = 0.1
learning_rate = 0.01

NOISE_STD = 0.1
TRAINING_DATA_NUMBER = 80000
BATCH_SIZE = 400
assert TRAINING_DATA_NUMBER % BATCH_SIZE == 0
BATCH_ITER_NUMBER = TRAINING_DATA_NUMBER // BATCH_SIZE
EPOCH = 100
TRAIN_ITER_NUMBER = EPOCH * BATCH_ITER_NUMBER

EVERY_N_ITER = 1000
EARLY_STOP_TRAIN_LOSS = 0.001
EARLY_STOP_VALID_LOSS_MULTIPLIER = 1.5
